# Generated by Django 5.2.8 on 2025-11-22 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Todo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Title of the TODO", max_length=200),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Detailed description of the TODO"
                    ),
                ),
                (
                    "due_date",
                    models.DateField(
                        blank=True, help_text="Due date for the TODO", null=True
                    ),
                ),
                (
                    "is_resolved",
                    models.BooleanField(
                        default=False, help_text="Whether the TODO is completed"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "TODO",
                "verbose_name_plural": "TODOs",
                "ordering": ["-created_at"],
            },
        ),
    ]
